# Generated by Django 4.2.16 on 2024-11-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservation_reservation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='tables',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.table'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
