# Generated by Django 4.2.16 on 2024-11-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_reservation_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_people',
            new_name='guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='0000-0000-0000', max_length=20),
        ),
    ]
