# Generated by Django 4.2.16 on 2024-11-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_num_people_reservation_guests_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='special_request',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='Jon Doe', max_length=100),
        ),
    ]
